apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-na-nuvem
  namespace: argocd
spec:
  project: devops-na-nuvem
  source:
    repoURL: https://github.com/kenerry-serain/devops-na-nuvem-aula-interna-jenkins-gitops
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default